### ISSUE TITLE
Checklist Stage 1

### ISSUE THREAD

**Issue by Bertus1998** [Bertus1998/TPUM-project-repository#1]
# Project Stage 1 Checklist

- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [ ] Object model representing process data
- [ ] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [ ] `Data` API is abstract
- [ ] `Logic` layer is clearly stated using language terms only
- [ ] `Logic` API is clearly stated
- [ ] `Logic` uses only the abstract `Data` layer API
- [ ] `Presentation` layer is clearly stated using language terms only
- [ ] mvvm and xaml is applied to implement GUI
- [ ] rective and interactive programming is used
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
