### ISSUE TITLE
My Checklist Stage 1.

### ISSUE THREAD

**Issue by Bertus1998** [Bertus1998/TPUM-project-repository#3]
# Project Stage 1 Checklist

- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] Object model representing process data
- [x] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [x] `Data` API is abstract
- [x] `Logic` layer is clearly stated using language terms only
- [x] `Logic` API is clearly stated
- [x] `Logic` uses only the abstract `Data` layer API
- [x] `Presentation` layer is clearly stated using language terms only
- [x] mvvm and xaml is applied to implement GUI
- [x] rective and interactive programming is used
- [x] Unit Test - layers are tested independently using abstract API
- [x] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
