### ISSUE TITLE
My checklist stage 2

### ISSUE THREAD

**Issue by Bertus1998** [Bertus1998/TPUM-project-repository#5]
- [ ] text is in C# and use .NET
- [ ] build succeeded
- [ ] all UT are green
- [ ] layers are clearly stated using language terms only
- [ ] `Data` API is abstract and contains object model representing process data
- [ ] prove that the data integration is implemented.
- [ ] `Logic` uses only the abstract `Data` layer API
- [ ] Communication between the client and the server should be made using the `Web Socket`
- [ ] reactive and interactive communication are used
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
